[[redirects]]
  from = "/api/*"
  to = "https://us-central1-got-auth-admin.cloudfunctions.net/api/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[redirects]]
  from = "/got-api/*"
  to = "https://gotauth-api.felixpy.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
